# Use the official Bun image as a base
FROM oven/bun:latest

# Set the working directory to the root of the project
WORKDIR /usr/pulse

# Copy the parent directory contents into the container at /usr/pulse
COPY . .

# Set environment variables
ENV NODE_ENV=production

# Move into the api directory
WORKDIR /usr/pulse/services/api

# Install dependencies using Bun
RUN bun install

EXPOSE 3030 

CMD ["sh", "-c", "until bash -c '</dev/tcp/127.0.0.1/5432' 2>/dev/null; do echo waiting for db...; sleep 1; done && bun run start"]
