app = "mystwright-api-production"

[build]
  dockerfile = "./Dockerfile"

[env]
  MODE = "production"

[[services]]
  internal_port = 3030
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.checks]]
  type = "http"
  interval = "5s"
  timeout = "5s"
  grace_period = "30s" # ⬅️ delay health checks until startup completes
  method = "GET"
  path = "/api/status" # ⬅️ make sure your app exposes this