app = "mystwright-api"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  MODE = "production"

[[services]]
  internal_port = 3030
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443